name: Check Branch Name

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Check if branch name is valid
        run: |
          if [[ ! "${{ steps.branch.outputs.name }}" =~ ^(feature/|bug fix/) ]]; then
            echo "Branch name is invalid. It must start with 'feature/' or 'bug fix/'."
            exit 1
          fi
